schoolShortName: nik-school
hostName: sugarizer.tools
sspserverName: Sugarizer Server
deployment:
    sspNamespace: none # Set to none if you plan to use Sugarizer Chart independent of Sugarizer School Portal
    https: true # HTTPs won't work on microk8s
    production: false # Required only if HTTPs is true. Use to switch between letsencrypt Staging and Production server. 
database:
    databaseUrl: ssp-mongodb
    replicaset: true
cluster: # Not required if HTTPS is false. Required only if you plan to use Sugarizer Chart independent of Sugarizer School Portal
    provider: aws # Options: gke, azure, aws, microk8s
    # If provider is gke
    gcpProjectId: null
    gcpServiceAccount: null
    # If provider is azure
    azureClientSecret: null
    azureSPAppId: null
    azureSubscriptionId: null
    azureTenantId: null
    azureDnsZoneResourceGroup: null
    azureDnsZone: null
    # If provider is aws
    awsClientSecret: null
    awsRegion: null
    awsAccessKeyId: null
    awsDnsZone: null
    awsRole: null
security:
    minPassSize: 4
    maxAge: '172800000'
    maxAgeTfa: '180000'
    serviceName: SchoolPortal
    secret: super.sugarizer.schoolportal.key
privacy:
    consentNeed: false
    policy: https://sugarizer.org/policy.html
