schoolShortName: nik-school
hostName: sugarizer.tools
deployment:
    sspNamespace: none # Set to none if you plan to use Sugarizer Chart independent of Sugarizer School Portal
    https: true # HTTPs won't work on microk8s
database:
    databaseUrl: mymongodb
    replicaset: true
cluster: # Not required if HTTPS is false. Required only if you plan to use Sugarizer Chart independent of Sugarizer School Portal
    provider: aws # Options: gke, azure, aws, microk8s
    # If provider is gke
    gcpProjectId: null
    gcpServiceAccount: null
    # If provider is azure
    azureClientSecret: null
    azureSPAppId: null
    azureSubscriptionId: null
    azureTenantId: null
    azureDnsZoneResourceGroup: null
    azureDnsZone: null
    # If provider is aws
    awsClientSecret: null
    awsRegion: null
    awsAccessKeyId: null
    awsDnsZone: null
    awsRole: null
